//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blender.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blenderEntities : DbContext
    {
        public blenderEntities()
            : base("name=blenderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<chef> chefs { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<recipe_category> recipe_category { get; set; }
        public virtual DbSet<require> requires { get; set; }
        public virtual DbSet<skill_level> skill_level { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<unit_system> unit_system { get; set; }
        public virtual DbSet<unit_type> unit_type { get; set; }
    }
}
