//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.authors = new HashSet<author>();
            this.recipe_category = new HashSet<recipe_category>();
            this.requires = new HashSet<require>();
        }
    
        public int recipe_id { get; set; }
        public string name { get; set; }
        public string instructions { get; set; }
        public int serves { get; set; }
        public int prep_mins { get; set; }
        public int cook_mins { get; set; }
        public int calories { get; set; }
        public string skill_level { get; set; }
        public byte[] visual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<author> authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_category> recipe_category { get; set; }
        public virtual skill_level skill_level1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<require> requires { get; set; }
    }
}
