//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unit()
        {
            this.requires = new HashSet<require>();
        }
    
        public string name { get; set; }
        public string type { get; set; }
        public string system { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<require> requires { get; set; }
        public virtual unit_system unit_system { get; set; }
        public virtual unit_type unit_type { get; set; }
    }
}
